package javaconsume;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Fri Jun 14 13:06:25 PET 2013
 */
public class AlphaClient implements Alpha {

    private com.bitmechanic.barrister.Transport _trans;

    public AlphaClient(com.bitmechanic.barrister.Transport trans) {
        trans.getContract().setPackage("javaconsume");
        trans.getContract().setNsPackage("javaconsume");
        this._trans = trans;
    }

    @Override
    public String Alpha(String a) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { a };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "Alpha.Alpha", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (String)_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

}
