package javaconsume;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Fri Jun 14 13:06:25 PET 2013
 */

public interface Alpha {

    public String Alpha(String a) throws com.bitmechanic.barrister.RpcException;

}

