package javaconsume;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Fri Jun 14 13:06:25 PET 2013
 */
public class BarristerMeta {

    public static final Long DATE_GENERATED = 1371230801674L;
    public static final String CHECKSUM = "d717f28051d92d610a92cb1a47608ee0";
    public static final String BARRISTER_VERSION = "0.1.5";
    public static final String PACKAGE_NAME="javaconsume";
    public static final String NS_PACKAGE_NAME="javaconsume";

}

