package javaconsume;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sun Jun 09 23:47:34 PET 2013
 */

public interface Lista {

    public Long[] lista(Long a, Long b) throws com.bitmechanic.barrister.RpcException;

}

