package javaconsume;

/**
 * DO NOT EDIT THIS FILE!
 * 
 * Generated by Barrister Idl2Java: https://github.com/coopernurse/barrister-java
 * 
 * Generated at: Sun Jun 09 23:47:34 PET 2013
 */
public class ListaClient implements Lista {

    private com.bitmechanic.barrister.Transport _trans;

    public ListaClient(com.bitmechanic.barrister.Transport trans) {
        trans.getContract().setPackage("javaconsume");
        trans.getContract().setNsPackage("javaconsume");
        this._trans = trans;
    }

    public Long[] lista(Long a, Long b) throws com.bitmechanic.barrister.RpcException {
        Object _params = new Object[] { a, b };
        com.bitmechanic.barrister.RpcRequest _req = new com.bitmechanic.barrister.RpcRequest(java.util.UUID.randomUUID().toString(), "Lista.lista", _params);
        com.bitmechanic.barrister.RpcResponse _resp = this._trans.request(_req);
        if (_resp == null) {
            return null;
        }
        else if (_resp.getError() == null) {
            return (Long[])_resp.getResult();
        }
        else {
            throw _resp.getError();
        }
    }

}

